//
//  BLERefer.h
//  BLE_Demo
//
//  Created by 先锋电子技术 on 16/5/17.
//  Copyright © 2016年 先锋电子技术. All rights reserved.
//

#ifndef BLERefer_h
#define BLERefer_h

#define     BLE_UUID_ALERT_NOTIFICATION_SERVICE   0x1811
#define     BLE_UUID_BATTERY_SERVICE   0x180F
#define     BLE_UUID_BLOOD_PRESSURE_SERVICE   0x1810
#define     BLE_UUID_CURRENT_TIME_SERVICE   0x1805
#define     BLE_UUID_CYCLING_SPEED_AND_CADENCE   0x1816
#define     BLE_UUID_DEVICE_INFORMATION_SERVICE   0x180A
#define     BLE_UUID_GLUCOSE_SERVICE   0x1808
#define     BLE_UUID_HEALTH_THERMOMETER_SERVICE   0x1809
#define     BLE_UUID_HEART_RATE_SERVICE   0x180D
#define     BLE_UUID_HUMAN_INTERFACE_DEVICE_SERVICE   0x1812
#define     BLE_UUID_IMMEDIATE_ALERT_SERVICE   0x1802
#define     BLE_UUID_LINK_LOSS_SERVICE   0x1803
#define     BLE_UUID_NEXT_DST_CHANGE_SERVICE   0x1807
#define     BLE_UUID_PHONE_ALERT_STATUS_SERVICE   0x180E
#define     BLE_UUID_REFERENCE_TIME_UPDATE_SERVICE   0x1806
#define     BLE_UUID_RUNNING_SPEED_AND_CADENCE   0x1814
#define     BLE_UUID_SCAN_PARAMETERS_SERVICE   0x1813
#define     BLE_UUID_TX_POWER_SERVICE   0x1804
#define     BLE_UUID_CGM_SERVICE   0x181A


#endif /* BLERefer_h */
